### ISSUE TITLE
Рефакторинг сервиса валидации

### ISSUE THREAD

**Issue by foobar1643** [richBlueElephant/phpClub#10]
Сейчас вся валидация происходит прямо в сервисах, сначала идут проверки на существование элемента в теле POST запроса, а затем статическим методом происходит валидация типов. Это неправильно и сложно тестировать. Нужно сделать отдельный сервис валидации:

* Сервис валидации будет принимать массив, значения в котором будут обязательными параметрами, которые нужно валидировать.
* У сервиса валидации будет метод addValidationRule(string $field, string $ruleName), который будет добавлять указанную функцию (правило валидации) к указанному полю в входящем массиве.
* У сервиса валидации будет метод validateFields(array $fields), который будет принимать аргументом массив полей, которые нужно валидировать. Массив всегда имеет формат [имя_поля => значение], при чем это необязательно может быть массив сформированный из объекта PSR-7 Request.
* Сама валидация происходит в два этапа. В validateFields() мы циклом проходимся по сохраненным ранее обязательным параметрам, и проверяем есть ли такой ключ в массиве $fields, если ключ есть, проверяем не пустой ли он (обрезав пробелы через trim()).
* Затем, если ключ в массиве есть, и он не пустой, мы смотрим в массив правил валидации для этого правила, если там есть какие-нибудь функции - вызываем их, если какая-то возвращает false - добавляем ошибку в массив ошибок.

Когда цикл заканчивается, возвращаем массив вида [имя_поля => сообщение_об_ошибке], или пустой массив если все хорошо.

@someApprentice отпиши что думаешь, не слишком ли переусложненно?

**Comment by someApprentice** [comment]
@foobar1643 Я думаю, что понятие "переусложненно" не должно препятствовать улучшению структуры. Как ты сказал, что это неправильно и сложно тестировать, значит нужно сделать отдельный сервис валидации. К тому же, что-то подобное я реализовывал когда писал студентов, и если бы я не писал 'casual' код, я бы выбрал именно такой способ.

**Comment by izac1** [comment]
Можно примерно показать пример вызова функций.

**Comment by kubk** [comment]
Есть же готовые валидаторы, например symfony/validator.
Пример использования этого валидатора вне symfony: http://symfony.com/doc/current/components/validator.html

**Comment by kubk** [comment]
Или вот попроще: https://github.com/alexgarrett/violin

**Comment by izac1** [comment]
@kubk С одной стороны ты прав зачем плодить в 100 раз велосипед с другой хочется написать самому чтоб получить опыт  @foobar1643 что скажешь ?

**Comment by foobar1643** [comment]
Тут все зависит сколько времени мы готовы на это потратить. Если делать такой валидатор как я описал в этой тут - при полном понимании задачи это не должно занять больше чем пол дня. С другой стороны, тогда нужно будет тратить время на ревью и правки по коду, и отладку сервиса под наши задачи. Ревью результатов работы желательно чтобы проводили все люди, которые работают над проектом, для того чтобы все имели понимание о том как работает данный класс и как его использовать. Далее также нужно будет тратить время на правки и повторный разбор и обсуждение этих правок. Я не против написать свой валидатор, но в данном случае это займет слишком много времени и это того не стоит (это исключительно мое мнение, потому что свободного времени у меня не очень много).

Я считаю что лучше взять уже готовый. Валидатор от симфони слишком большой, я думаю второй вариант который предложил @kubk довольно неплохой, правда я не изучал его особо.

@izac1 если ты все таки хочешь написать свой чтобы получить опыт - это тоже не проблема, только наверное нужно это согласовать как-нибудь со всеми.

**Comment by kubk** [comment]
Стоит отметить, что некоторым методам явно не место в классе Validator.
Например метод [validateThreadSubject](https://github.com/someApprentice/phpClub/blob/master/src/Service/Validator.php#L24) логичнее поместить в сервис для работы с тредами. Этот метод используется только в одном месте, вот [тут](https://github.com/someApprentice/phpClub/blob/master/src/Service/Threader.php#L53), это низкоуровневые кишки, которые нужно инкупсулировать внутри класса для работы с тредами, а не делать глобально доступной статикой. Вот [тут](https://github.com/codedokode/task-checker/blob/master/src/TextReader/Reader.php#L66) похожая ситуация, никаких глобальных функций валидации нет.
Часть методов вроде validateThreadLink, validateChainLink, validateRegistrationLink, validateLogoutLink вообще нигде не используются. И зачем валидировать ссылки регистрации и логаута?

**Comment by kubk** [comment]
Закрываю, чтобы не сбивать новых людей с толку. В слаке обсуждали возможный переход на SF4, который по своей сути тоже микрофреймворк, поэтому будем использовать компоненты симфони.
