### ISSUE TITLE
Кеширующие заголовки в ответе API

### ISSUE THREAD

**Issue by codedokode** [richBlueElephant/phpClub#105]
Я заметил, что в ответе API для превью постов https://phpclub.tech/api/board/get/message/1380677/ нет заголовков, разрешающих кеширование. Из-за этого при каждом наведении мыши на ссылку пост запрашивается с сервера заново. Посты меняются редко (меняется только список ответов на них при добавлении новых постов на сервере). Возможно, имеет смысл поставить заголовок безусловного кеширования Expires минут на 5-15, чтобы исключить лишние запросы к API. Безусловное кеширование значит, что браузер сохранит ответ на указанное время и будет отдавать его из кеша без проверки валидности на сервере. Таким образом, единственный возможный негативный эффект - при добавлении нового ответа на пост его не будет в refmap превьюшки в течение указанного времени.

В Симфони есть уже готовые методы вроде setExpires для этого: https://symfony.com/doc/current/http_cache/expiration.html

**Comment by kubk** [comment]
Хорошее предложение, мы можем использовать пакет slim-httpcache:
- http://www.slimframework.com/docs/v3/features/caching.html
- https://github.com/slimphp/Slim-HttpCache/blob/master/src/CacheProvider.php#L70

**Comment by kubk** [comment]
@codedokode Обнаружил, что запрос к АПИ для получения поста выполняется только в том случае, если пост не из выбранного треда: https://github.com/richBlueElephant/phpClub/blob/c39c20b2eb1a8a2f503fe0fdb531fccfc44d3184/public/media/js/script.js#L166
На практике это означает, что запрос к АПИ выполняется в основном для ОП-постов, так как на другие посты из предыдущих тредов ссылаются редко:

![image](https://user-images.githubusercontent.com/22447849/63222008-4784d700-c1aa-11e9-977f-0c6ca2f95501.png)

Для ОП-поста ответы не генерируются: https://github.com/richBlueElephant/phpClub/blob/master/src/ThreadImport/ChainManager.php#L31

Предлагаю выставить время кеша на неделю.

**Comment by codedokode** [comment]
@kubk основная проблема была в том, что нет особого смысла делать повторные запросы, если пользователь просто несколько раз навел мышь на один и тот же пост. Что касается времени ответа сервера - может у кого-то интернет, например, мобильный с пингом в полсекунды и ему получить ответ из кеша будет просто удобнее.

Согласен, что с хитрым кешированием незачем пока заморачиваться, кеш на 15 минут эту проблему полностью решает.
