### ISSUE TITLE
Syntax error or access violation: 1064 offset out of bounds (offset=11060, max_matches=10000

### ISSUE THREAD

**Issue by kubk** [richBlueElephant/phpClub#106]
Проблему можно воспроизвести, если сделать поиск по слову, для которого Sphinx находит больше 10-и тысяч результатов, например "PHP" и перейти на последнюю страницу пагинации. Проблема возникает из-за того, что метод, считающий количество результатов поиска для пагинации, [использует](https://github.com/richBlueElephant/phpClub/blob/master/src/Pagination/SphinxAdapter.php#L26) `COUNT(*)`, который игнорирует лимитирующие параметры ('limit', 'max_matches') и возвращает все строки, подходящие под поиск. В результате строк больше 10-и тысяч, мы переходим на последнюю страницу и получаем ошибку, так как запрашиваем записи начиная с 11060 при лимите 10000. Способы решения:
- Вместо `COUNT(*)` использовать другой способ получения количества результатов, который будет учитывать лимит.
- Не использовать Sphinx, а попробовать полнотекстовый поиск PostgreSQL
- Сделать лимит больше 10-и тысяч. Это будет влиять на производительность поиска.

**Comment by codedokode** [comment]
Вообще, один из вариантов - это просто на уровне PHP ограничивать кол-во результатов 10 000 (или даже меньше) и подстроить пагинацию под это (т.е. написать `$count = min($count, MAX_SEARCH_RESULTS)`  ). Так как я плохо представляю себе, кому может понадобиться читать 10 000 постов подряд. Если хочется сделать совсем хорошо, можно добавлять предупреждение про реальное число результатов. 

Замена на другой движок вряд ли что-то изменит, так как сортировка результатов требует подгружать их в память и лимит используется для защиты от слишком высокого потребления памяти (сфинкс ведь может использоваться на БД с сотнями миллионов записей и огромным числом параллельных запросов). Другой движок тоже будет либо иметь лимит, либо не будет иметь защиты от переполнения памяти, либо задействует временные файлы на диске.

Гугл по моему так же имеет ограничение на число страниц.

**Comment by kubk** [comment]
@codedokode Спасибо, хороший вариант.
