### ISSUE TITLE
Логгирование ошибок в production окружении

### ISSUE THREAD

**Issue by foobar1643** [richBlueElephant/phpClub#11]
Сейчас когад происходит любое исключение, при display_errors = 0, пользователю показывается стандартная заглушка слима, которая говорит о том что что-то пошло не так. При этом исключения ни в какой лог не пишутся, мы о них никогда не узнаем.

Нужно добавить к слиму свой exception handler, который будет писать ошибки в какой-нибудь лог (я думаю хватит и обычной встроенной функции error_log). Как добавить обработчик исключений [описано тут](https://www.slimframework.com/docs/handlers/error.html).

**Comment by kubk** [comment]
Лучше наверное использовать Monolog: https://github.com/akrabat/slim3-skeleton/blob/master/app/dependencies.php#L32

В Monolog легко добавлять слушатели ошибок, которые будут отсылать их, к примеру, в гиттер или телеграм, чтобы оперативно получать сообщения об ошибках.

**Comment by someApprentice** [comment]
Поддерживаю идею с Monolog'ом

**Comment by izac1** [comment]
Поддерживаю идею с Monolog'ом тоже.
