### ISSUE TITLE
Пагинация на странице поиска

### ISSUE THREAD

**Issue by foobar1643** [richBlueElephant/phpClub#12]
Сейчас все результаты на странице поиска выводятся сразу, без какой-либо пагинации. Это неудобно в использовании, так еще и даст нагрузку на БД, если результатов будет под 1k.

Нужно сделать пагинацию, делать её нужно на уровне Sphinx. У него есть какой-то параметр в запросе SHOW META, который возвращает количество совпавших элементов без учета LIMIT в запросе.

**Comment by codedokode** [comment]
Также, у sphinx есть еще параметр OPTION MAX_MATCHES, который ограничивает число возможных результатов и по умолчанию как раз по моему равен 1000. И, если я не путаю, если LIMIT не указывать, то он там равен чему-то вроде 20.

http://sphinxsearch.com/docs/current/sphinxql-select.html

> LIMIT clause. Both LIMIT N and LIMIT M,N forms are supported. Unlike in regular SQL (but like in Sphinx API), an implicit LIMIT 0,20 is present by default.

**Comment by someApprentice** [comment]
Для [SphinxAdapter'а](https://github.com/richBlueElephant/phpClub/blob/master/src/PagerfantaAdapter/SphinxAdapter.php) не хватает тестов

Не уверен как можно это тестировать

У кого-нибудь есть какие-нибудь идеи?

**Comment by kubk** [comment]
@someApprentice :+1: 

https://github.com/richBlueElephant/phpClub/blob/master/src/PagerfantaAdapter/SphinxAdapter.php#L41
Тут нельзя SELECT COUNT(*) сделать?

https://github.com/richBlueElephant/phpClub/blob/master/src/PagerfantaAdapter/SphinxAdapter.php#L61
Думаю limit и offset лучше подставлять через плейсхолдеры:
$query->bindValue(':limit', $limit, \PDO::PARAM_INT);
$query->bindValue(':offset', $offset, \PDO::PARAM_INT);

> Не уверен как можно это тестировать

Сама логика в классе простая, он ведь адаптирует данные с sphinx и БД для библиотеки pagerfanta, не вижу смысла здесь юнит-тестировать. В будущем может быть интеграционный тест можно сделать с реальным sphinx'ом - заиндексировать постов 20 для теста и проверить что поиск выдаёт нужные результаты.

@foobar1643 issue можно закрывать? Ты что-то про show meta в описании писал.

**Comment by codedokode** [comment]
Этот адаптер получится тестировать только в рамках интеграционного тестирования код + сфинкс. Так как он отпрваляет запросы в сфинкс через PDO и мы вряд ли можем как-то проверить их.
