### ISSUE TITLE
На сайте пропали обратные ссылки (ответы на пост) 

### ISSUE THREAD

**Issue by codedokode** [richBlueElephant/phpClub#121]
Под постами нет ссылок на ответы на этот пост, например тут: 

- https://phpclub.tech/pr/res/1511146.html Пост №1511237 ссылается на  №1511230  , но нет обратной ссылки
- https://phpclub.tech/search/?q=%D0%BD%D0%B5+%D0%B1%D1%8B%D0%BB+%D1%80%D0%BF%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D1%8B%D1%81%D1%82%D0%BE%D0%BC тут тоже нет обратных ссылок

А раньше вроде как были.

**Comment by kubk** [comment]
Подтверждаю. Это потому что временно не работают цепочки ответов. Их пришлось отключить так как при импорте новых тредов появлялась ошибка БД - UniqueContstraintViolation. Как воспроизвести локально - на пустую БД накатить миграции и запустить скрипт по импорту тредов: 
```
./bin/console import-threads --source=arhivach
./bin/console import-threads --source=2ch-api

**Comment by kubk** [comment]
Исправлено в #122
