### ISSUE TITLE
Ошибка Doctrine при попытке импортировать миграции

### ISSUE THREAD

**Issue by foobar1643** [richBlueElephant/phpClub#2]
Происходит только если к PHP подключено расширение для работы с Redis.

В консоли пишу

``` bash
vendor/bin/doctrine orm:schema-tool:create

```

Получаю

```
PHP Warning:  Redis::connect(): connect() failed: Connection refused in /var/www/phpClubOrig/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Setup.php on line 138

```

Видимо доктрина автоматически нашла дополнение Redis и зачем-то пытается подключится к Redis серверу. Временное решение - отключить расширение для работы с Redis, без него данной ошибки не происходит.

**Comment by foobar1643** [comment]
Хочу отметить, что в БД MySQL из-за этой ошибки ничего не записалось.

**Comment by foobar1643** [comment]
kubk 22:16
Проблема, по-видимому, в фабричном методе: https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Tools/Setup.php#L122
Тут видно что в этом фабричном методе по дефолту грузится всё, что только можно, а потом создаётся объект Configuration: https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Tools/Setup.php#L152
Какой я вижу выход: создавать Configuration вручную, без фабричных методов.
То есть внести изменения в этот код: https://github.com/someApprentice/phpClub/blob/master/src/Bootstrap.php#L42

**Comment by codedokode** [comment]
Я тут мимо проходил. @foobar1643 все верно описал, это просто какая-то автоконфигурация. Доктрине нужен кеш для хранения метаданных о сущностях, и видимо увидив наличие редиса, она решила его задействовать для этой цели. То есть верно, надо отключить все это автоопределение и прописать конфигурацию явно, в том числе кеш метаданных и способ генерации прокси-объектов.

На дев-сервере можно не использовать кеш и не хранить прокси, пусть они сами генерируются в памяти каждый раз (или же надо постоянно проверять актуальность кеша), а на продакшене обычно все это генерируется при деплое, сохраняется и во время работы на это время уже не тратится. Можно использовать на продакшене для кеша метаданных обычные php файлы, они закешируются в OPCache и будут фактически браться из shared memory.

- http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/advanced-configuration.html

```php
$config->setMetadataCacheImpl($cache);
...
$config->setProxyDir('/path/to/myproject/lib/MyProject/Proxies');
```

Вот тут и задается кеш метаданных и папка для прокси. Кеш запросов использовать не советую без веской причины.
