### ISSUE TITLE
Переработать frontend

### ISSUE THREAD

**Issue by someApprentice** [richBlueElephant/phpClub#21]
(( Полностью написать собственный с нуля ))

**Comment by foobar1643** [comment]
Как смотришь на то, чтобы сделать на TypeScript и ES6?

**Comment by kubk** [comment]
Думаю, что тема важная. Сейчас для отображения тредов приходится хранить ненужные данные вроде md5 файла или опции nsfw, в противном случае JS-код макабы работает непредсказуемо. То есть под макабу даже придётся подстраивать скрипт импорта треда из других источников (архивача, например). Прекрасным решением этой проблемы стала бы кастомная вёрстка.

Насколько я понял, задачу можно разбить на отдельные слабо связанные подзадачи:
- Резиновая вёрстка. [Тут](https://github.com/codedokode/board-markup) что-то может пригодиться
- Код, отвечающий за то, чтобы при клике на миниатюру изображения аяксом подгружалась полная версия этого изображения и позиционировалась абсолютно. На 2ch.hk полная версия изображения драггабельна.
- Код, отвечающий за создание цепочки ответов. Задание чем-то напоминает [это](https://gist.github.com/codedokode/ce30e7a036f18f416ae0#5-Всплывающее-окно-сложная)

**Comment by someApprentice** [comment]
@foobar1643, я не уверен... Мне нужно сначала лучше изучить JavaScript чтобы принять решение

**Comment by foobar1643** [comment]
@someApprentice ES6 очень улучшает поддерживаемость кода возможностью разделить его на модули. Также есть полезный синтаксических сахар, который делает JavaScript более удобным.
Про все новые вещи можешь тут посмотреть http://es6-features.org/

TypeScript делает все еще лучше, добавляя строгую типизацию, с возможностью тайпхинтить элементы в массивах и объектах. Сам TypeScript это не отдельный язык программирования, а скорее дополнение к JS (он кстати поддерживает все вещи из ES6). Про него можешь документацию почитать https://www.typescriptlang.org/docs/home.html

**Comment by kubk** [comment]
Небольшой апдейт по задаче - не нужно дополнительный данных хранить из-за макабы, достаточно длины/ширины оригинала + путей к оригиналу и превью. Так что толку от своего фронта мало, проще вырезать из файла swag.js весь код, который не касается создания цепочки ответов и подгрузку полной версии изображения (функция expand).

@foobar1643 ИМХО TypeScript оправдывает себя в сложных приложениях, на мешанине из функций вряд ли получится написать приложение вроде этого: https://github.com/foobar1643/arkanoid
Но в phpClub достаточно 2-х функций - одна для построения цепочки сообщений, вторая для подгрузки полной картинки. И можно использовать уже работающие функции из swag.js
Я могу попробовать вырезать всё лишнее оттуда, если такой подход устроит, тогда отложим задачу в долгий ящик.

**Comment by codedokode** [comment]
Насчет фронтенда макабы - он вырос из какого-то браузерного расширения. Авторы расширения не могли ничего сделать с серверной частью. Потому, например, при наведении на ссылку на пост в другом треде оно по моему загружает тред целиком, и достает из него нужный пост. То есть это расширение, прикрученное к существующему серверному коду и верстке.

Соответственно, в нашем случае мы можем делать с версткой и серверным кодом что угодно и не ограничивать себя. Ну и так как это архив, то многие функции могут и не потребоваться. Да даже если картинка будет открываться не в попапе, а в новой вкладке - все равно ведь архивом можно нормально пользоваться.

> Код, отвечающий за то, чтобы при клике на миниатюру изображения аяксом подгружалась полная версия этого изображения 

Можно без аякса, просто в img прописать data-large-src="...", а можно заморочиться и использовать [srcset](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images), который позволяет браузеру выбрать картинку, подходящую под ширину канала, размер и плотность пикселей на экране. Пример кода: 

```html
<img srcset="elva-fairy-320w.jpg 320w, elva-fairy-480w.jpg 480w, elva-fairy-800w.jpg 800w"
     sizes="(max-width: 320px) 280px, (max-width: 480px) 440px, 800px"
     src="elva-fairy-800w.jpg" alt="Elva dressed as a fairy">
```

Старые браузеры игнорируют `srcset` и отображают картинку из `src`. Соответственно, в случае поддержки `srcset` можно просто сделать `$(image).clone().appendTo(popup);` и оно должно само подгрузить большую картинку.

Насчет тайпскрипта - советую померять сначала, сколько времени занимает компиляция. А то люди добавляют в проект Babel, а потом осознают что после каждой правки им надо ждать по полминуты, пока он скомпилирует реакт. Всегда удобнее, когда в dev окружении все работает сразу. Так-то мне например идея тайпскрипта нравится, но удобно ли будет с ним работать?

**Comment by foobar1643** [comment]
> Насчет тайпскрипта - советую померять сначала, сколько времени занимает компиляция. А то люди добавляют в проект Babel, а потом осознают что после каждой правки им надо ждать по полминуты, пока он скомпилирует реакт. Всегда удобнее, когда в dev окружении все работает сразу. Так-то мне например идея тайпскрипта нравится, но удобно ли будет с ним работать?

@codedokode Там все достаточно быстро, если не транспайлить через Babel. Т.е. для дев окружения нужно будет брать новый браузер, и компилировать через tsc. Babel все равно нужен будет, для поддержки старых браузеров, билд через него можно будет запускать только при деплойменте через CI.

Я еще потестирую насколько быстро работает tsc и как с поддержкой кода в последнем хроме (хотя там от самого кода зависит, наверное).

**Comment by someApprentice** [comment]
Добавлю сюда задачу, чтобы не забыть:

-Убрать прокрутку у длинных постов

**Comment by someApprentice** [comment]
Напомню себе: перенести строки https://github.com/someApprentice/phpClub/blob/53d4739cadb6387966e7ba40c7065d0b4414e920/templates/board.phtml#L12-L13 чтобы обработчик https://github.com/someApprentice/phpClub/blob/53d4739cadb6387966e7ba40c7065d0b4414e920/public/media/js/swag.js#L611 можно было повесить на эти родительские элементы, а не каждый класс .thread

**Comment by kubk** [comment]
@someApprentice сейчас в проекте закоммичены вендорные файлы, пример: https://github.com/someApprentice/phpClub/tree/master/public/media/less

Думаю лучше это не коммитить и настроить установку фронтенд зависимостей через пакетный менеджер. FontAwesome, jQuery и Twitter Bootstrap можно ставить через composer: https://github.com/kubk/students/blob/master/composer.json#L10
Так в будущем будет проще обновлять зависимости.

Можно указать композеру, чтобы он после install выполнял команду, которая будет автоматом копировать файлы из vendor в public:
- https://github.com/kubk/students/blob/master/composer.json#L29
- https://github.com/kubk/students/blob/master/scripts/publish-frontend.sh 
(в моём случае файлы не копируются, создаются символические ссылки)

Для всех вендорных файлов лучше создать отдельную папку (public/vendor), и её полностью добавить в .gitignore

**Comment by someApprentice** [comment]
На будущее:

Добавить [Webpack Encore](https://symfony.com/doc/current/frontend.html)

**Comment by someApprentice** [comment]
Напоминание для себя:

Добавить в поисковой форме, после отправки запроса, текст запроса
Добавить поисковую форму над выводом результатов

**Comment by someApprentice** [comment]
@codedokode 

> Старые браузеры игнорируют srcset и отображают картинку из src. Соответственно, в случае поддержки srcset можно просто сделать $(image).clone().appendTo(popup); и оно должно само подгрузить большую картинку.

В миниатюре тоже же будет отображаться изображение из srcset, если экран будет широким, ведь нет?

**Comment by codedokode** [comment]
@someApprentice  По идее это долдно работать так. Мы указываем в `srcset` ссылки на все имеющиеся картинки и их размеры, а в `sizes` - как размер картинки зависит от размера окна браузера. Браузер через `sizes` вычисляет примерный размер картинки, подбирает подходящую из `srcset` и загружает ее.

Так что да, получается, что размер картинки вычисляется из размера окна и это может не сработать. Ну или придется обновить у копии картинки атрибут `sizes`. Что-то я об этом не подумал.

Более того, я делал тестирование этой фичи, и она работает не идеально. Ну например, при изменении размера окна, повороте моб. устройства или изменении размера блока с картинкой в некоторых браузерах там может продолжать использоваться старая картинка низкого разрешения. В сети даже можно найти советы ловить событие `resize` и яваскриптом обновлять `src`, чтобы заставить браузер поменять источник картинки.


> В миниатюре тоже же будет отображаться изображение из srcset, если экран будет широким, ведь нет?

Получается, что да, если только не обновить атрибут `sizes`.

**Comment by someApprentice** [comment]
@codedokode я переписал js код, который повторяет поведение макабы, но я хочу смотреть в будущее и применять совеременные технологии, поэтому нужен ваш совет, стоит ли применять такой способ.

Кроме того, я обнаружил, что превью видеозаписей выводятся с помощью уменьшенного изображения, и склонировать само видео не получится.

На всякий случай приложу код pop up'а:

```
    $(window).click(function(e) {
        var lightbox = $('#lightbox');

        var a = $('a', '.file');

        if ($(a).has(e.target).length == 0 && !$(a).is(e.target)) {
            if (!$('.fullsize').is(e.tareget)) { //somehow it doesn't works
                $(lightbox).hide();
                $(lightbox).empty();
            }
        } else {
            $(lightbox).empty();

            var src = $(e.target).parent().attr('href');
            var ext = src.split('.').pop().toLowerCase();

            switch (ext) {
                case 'jpg': case 'png': case 'gif':
                    var content = $('<img/>', {class: 'fullsize', src: src});
                    break;

                case 'mp4': case 'webm':
                    var content = $('<video/>', {class: 'fullsize', src: src, controls: 'controls'});
                    break;

                default:
                    window.open(src, '_blank'); 

                    return false;
            }

            $(lightbox).append(content);
            $(lightbox).show();

            // sometimes it works wrong
            $(content).ready(function() {
                var width = $(window).width();
                var cWidth = $(content).width();

                var height = $(window).height();
                var cHeight = $(content).height();

                var top = (height - cHeight) / 2;
                var left = (width - cWidth) / 2;

                $(lightbox).css('top', top);
                $(lightbox).css('left', left);
            });
        }
```

**Comment by codedokode** [comment]
@someApprentice по коду: 

Для того, чтобы отлавливать клики с фильтром по определенному селектору, есть `$.on`: http://api.jquery.com/on/

```js
$(window).on('click', '.file a', function () {
    var link = $(this);
});
```

Вообще, тут лучше было бы дать ссылке какой-то класс и указать в селекторе его.

> var a = $('a', '.file');

Во-первых, это короче записать как `$('.file a')` (или имелось в виду `$('a, .file')`?).

Во-вторых, эта команда делает поиск по всему дереву DOM элементов `a` внутри элементов `.file`, думаю, что это довольно неэффективно, так как на большой странице это дерево огромное, и искать все ссылки на странице не треуется. Мы ищем сотню элементов только ради того, чтобы проверить, есть ли в этом списке один элемент.

Для проверки, что мы кликнули на элемент, лучше всего использовать `$.on`, или конструкцию `$(target).closest('.file a').length` - она делает поиск от элемента к корню дерева. Опять же, вместо сложного селектора тут лучше было бы вписать только один класс.

Еще есть `$(target).is('.file a')` - но она проверяет на точное совпадение с селектором.

> var src = $(e.target).parent().attr('href')

Такие конструкции писать плохо, так как они легко ломаются - достаточно добавить одну обертку и `parent()` перестанет указывать куда нужно. Лучше всего искать родителя с помощью `closest()` по классу. На все ключевые элементы поставить свой класс. Для выбора названий классов лучше всего (по моим ощущениям) использовать БЭМ, а в верстке макабы классы расставлены от балды без всякой логики.

> var ext = src.split('.').pop().toLowerCase()

Это лучше вынести в функцию с понятным именем. Не надо писать код стеной.

> default:
>        window.`open`(src, '_blank'); 

Это вообще наверно писать не надо, лучше просто выйти из обработчика, не отменяя действие по умолчанию.

>  $(content).ready

Вообще, центрирование идеальнее всего сделать средствами CSS (через `position: absolute`, `table-cell` либо `flexbox`, последний умеет ужимать картинку до размера контейнера), либо, если невозможно, то надо ловить события `load`/`error` на картинке, а не ready.

Тут https://api.jquery.com/ready/ написано, что ready обозначает событие загрузки документа DOM, и с его помощью нельзя определить момент загрузки картинки. Для картинки надо слушать на ней события load/error. Для видео - не помню, надо посмотреть в MDN информацию про тег video.

Кстати, при изменении размера окна надо перецентрировать картинку заново. Потому лучше было бы поискать способы центрировать ее через CSS.

Еще надо проверить, как это работает на маленьких экранах (моб. устройствах). Там нужно возможность зумить и двигать картинку. Возможно, что там проще просто открывать картинку в новой вкладке браузера.

`preventDefault` лучше делать только, если мы успешно обработали клик, а не всегда. 

Для закрытия картинки лучше бы предусмотреть кнопку-крестик, а также можно положить под картинку снизу прозрачную или полупрозрачную подкладку и ловить клики на ней.

Кстати, у меня в браузерах 2-летней давности, ни в FF, ни в Хроме jsfiddle уже не работает. Такие там "специалисты".

**Comment by kubk** [comment]
https://github.com/richBlueElephant/phpClub/blob/ff2a292d87c2ce270d21d9eb89f8638783c6ecca/templates/post.phtml#L16
@someApprentice тут нет опечатки? `date` вместо `data`

Вообще в этом issue много комментариев - это нормально, но неясно на каком этапе сейчас всё находится, что сделано и что предстоит сделать, что является критерием для закрытия issue. Гораздо проще себя заставить что-то сделать когда есть список из мелких подзадач. Считаю, что вёрстка уже готова и сделана хорошо, превью картинок работают. Осталось разобраться с вендорными файлами (42 МБ шрифтов в репозитории это не норм), что ещё? Ставим фронтенд зависимости через Composer и копируем скриптом только нужное в `public/vendor`.

Если интересно, markdown разметка поддерживает подзадачи: https://blog.github.com/2014-05-14-nested-task-lists/
Это гораздо удобнее и нагляднее, чем разрозненные комментарии вперемешку с обсуждениями.
