### ISSUE TITLE
Параметры для подключения к Sphinx вынести в файл конфигурации

### ISSUE THREAD

**Issue by foobar1643** [richBlueElephant/phpClub#3]
Для подключения к удаленному поисковому серверу пришлось менять адрес в исходниках, нужно сделать или отдельный конфиг для сфинкса, или добавить секцию в уже существующий config/config.ini.

**Comment by someApprentice** [comment]
Напомню здесь, что можно попробовать использовать QueryBuilder заместо PDO, если это возможно.

**Comment by kubk** [comment]
@foobar1643 конфиг сфинкса не поддерживает переменные окружение, поэтому сделал по старинке через .example файл, который нужно будет скопировать после установки приложения: https://github.com/richBlueElephant/phpClub#installation

@someApprentice нам ведь пока не нужно динамически строить запрос.
