### ISSUE TITLE
Роут формы поиска

### ISSUE THREAD

**Issue by someApprentice** [richBlueElephant/phpClub#34]
Форма отправляет запрос поиска на `search?q=...`, но Slim добавляет слэш перед параметром `?q`
Даже если написать роут таким образом `/search?q={searchQuery}/`, то он, всё равно, не обработается, и форма будет перенаправляться на `/search/?q=...`

На текущий момент, роут работает по `/search/{searchQuery}`, поэтому самым простым решением кажется, сделать отправку и перенаправление формы по средством JS
Однако, хотелось бы выяснить почему у Slim'а такое поведение, и исправить это, без прибегания к скриптам (работа с отключенным JS - всегда хорошо)

**Comment by foobar1643** [comment]
В роутере нельзя обработать Query параметр. Самый простой способ без скриптов - это переделать роут, чтобы запрос для поиска брался из query параметра, а не из плейсхолдера как сделано сейчас. Тогда будет работать даже с отключенным JS.

**Comment by kubk** [comment]
Тест

**Comment by codedokode** [comment]
Да, роутер не разбирает параметры за знаком вопроса и в таких случаях обычно делают роут `/search/` и уже в контроллере достают поисковый запрос. JS скрипты тут привлекать не стоит, так делают  SEO-шники, чтобы создать "страницы" с нужными ключевыми словами.
