### ISSUE TITLE
Предложение: улучшить тайтлы

### ISSUE THREAD

**Issue by codedokode** [richBlueElephant/phpClub#36]
Сейчас у всех страниц тайтл "phpClub". Это имеет такие недостатки: 

- при добавлении в закладки название закладки малоинформативно
- заголовок вкладки/окна ничего не говорит
- в поисковой выдаче заголовок малоинформативен (пример: https://www.google.ru/search?q=site:phpclub.tech+%D0%B3%D0%BE%D1%81%D1%82%D0%B8%D0%BD%D0%B8%D1%86%D0%B0&newwindow=1&dcr=0&gbv=1&sei=lKCMWsS7IpCYkwWKg5Vw )
- может ухудшаться позиция страниц в выдаче поисковых систем из-за одинаковых тайтлов

Наверно было бы лучше сделать более осмысленные тайтлы, например (это только предложение): 

- для главной: "Архив тредов клуба изучающих PHP" или "Список тредов | Клуб PHP" или "Оглавление"
- для треда - "Клуб изучающих PHP 97" или "Тред 97, архив" 
- для /chain/XXX/ - "Ответы на пост ..." 

То есть у нас есть строка ограниченной длины и в идеале нужно вместить в нее как можно более точное описание страницы. 

В тайтл можно добавлять, а можно не добавлять название сайта. Это иногда помогает в поиске - например, у меня на сайте в тайтле приписано "PHP с нуля" и по этим словам сайт хорошо ранжируется.  С другой стороны, это удлиняет тайтл, что плохо.

**Comment by kubk** [comment]
Спасибо, делаем так:
- Для главной - Архив тредов клуба изучающих PHP
- Для треда - "Клуб изучающих PHP 97 | Архив"
- Для цепочки ответов - "Ответы на пост # ..."

https://github.com/richBlueElephant/phpClub/commit/607d701f4be6cd97694fc47326bea063542fca82

Если что - issue можно переоткрыть после закрытия.
