### ISSUE TITLE
Префикс для имен индексов в Sphinx

### ISSUE THREAD

**Issue by foobar1643** [richBlueElephant/phpClub#4]
index_posts - не очень удачное название, у меня уже может быть такой индекс в сфинксе. Лучше бы сделать что-то вроде phpClub_posts, или что-нибудь подобное уникальное. Так же, для удобства этот префикс можно подставлять автоматически из файла конфигурации для Sphinx (по нему отдельная задача #3).

**Comment by codedokode** [comment]
Дополню еще. Если надо например запускать 2 копии проекта, то по моему опыту, проще просто поднять отдельный демон сфинкса (чем например делать опции в конфиге для смены префикса). Современные ОС используют systemd, в нем просто пишем конфиг и создаем второй демон на другом порту, с другими папками для логов, данных, pid-файлов и тд. Либо, если это дев-сервер, пишем шелл-скрипт для запуска/остановка демона вручную, когда он нужен.

То есть не советую заморачиваться с префиксами в конфиге, имхо тут усложнение кода того не стоит. Фиксированный префикс - почему бы и нет.

**Comment by kubk** [comment]
@codedokode Согласен, ещё удобно создавать несколько systemd сервисов для удобного управления несколькими версиями одной программы.

@foobar1643 Думаю, раз добавлен sphinx.conf.example файл, то каждый может сам поменять название индекса, если нужно.
