### ISSUE TITLE
Редиректы с поддоменов/http

### ISSUE THREAD

**Issue by codedokode** [richBlueElephant/phpClub#40]
Один и тот же контент доступен по разным ссылкам: 

- http://www.phpclub.tech/
- https://www.phpclub.tech/ (тут правда неправильный сертификат)
- https://phpclub.tech/

Наверно, стоит настроить редирект 301 с первого на последний URL (с сохранением пути, query string и hash). Сейчас в поиск, например, попадают именно HTTP-страницы с www. Редирект 301 поможет поисковым системам исправить ссылки. 

Наличие контента на 2 доменах может ухудшить индексацию, так как поисковик будет думать, что это 2 отдельных сайта.

**Comment by someApprentice** [comment]
Добавил в настройку Апача строку `RewriteRule "^(.*)$" "https://phpclub.tech$1" [R=301,QSA]`

Должно работать
