### ISSUE TITLE
Парсер: не парсится код из старых тредов

### ISSUE THREAD

**Issue by codedokode** [richBlueElephant/phpClub#42]
Пост https://phpclub.tech/pr/res/333445.html#333513 (тред 13) обрывается на слове "функцией:". В моей копии треда в этом посте дальше идет код, вот кусок HTML (для читаемости вырезал часть и добавил переносы строк): 

```html
...
Писать нечитаемую лапшу&#44; конечно&#44; неправильно. 
Лучше сделать проверку отдельной функуией: 
<br /><br />
<pre><code><br />
$age = isset($_POST[&#39;age&#39;]) ? intval($_POST[&#39;age&#39;]) : 0;<br />
$name = isset($_POST[&#39;name&#39;]) ? $_POST[&#39;name&#39;] : &#39;&#39;;<br />
<br />
$data = array(<br />
    &#39;age&#39; =&gt; $age&#44;<br />
    &#39;name&#39; =&gt; $name<br />
);
<br /><br />
<br /></code></pre>
<br /><br />
Если полей много&#44; то вместо копипасты ....
```

Вот дерево DOM: 

```
<td class="reply">
    ...
    <blockquote id=​"m333446" class=​"postMessage">​
        <p>​…​</p>​
        <pre>​…​</pre>​
        <br>​
        <br>​
        "- у определений функций и классов так:"    
       ...
```

Видимо в старых тредах была разметка для вставки кода в пост.

Я протестировал в консоли разработчика [используемый для выборки текста XPath](https://github.com/richBlueElephant/phpClub/blob/b7ab387b76c9cb91d81426fe797553b8aaaa28f9/src/ThreadParser/DvachThreadParser.php#L36) и действительно, он находит только 2 абзаца из всего текста.

```js
// Добавил точки для относительности
var textPath = './/blockquote/p | .//blockquote[not(p)]';
r2 = document.evaluate(textPath, post, null, XPathResult.ORDERED_NODE_SNAPSHOT_TYPE, null);
r2.snapshotItem(0)
// <p>​…​</p>​
r2.snapshotItem(1)
// <p>​</p>​
r2.snapshotItem(2)
// null
```

Потому есть предложение: брать все содержимое blockquote, а дальше можно обходить элементы по очереди (вглубь), известные конвертровать в текст и выдавать ошибку или варнинг при обнаружении неизвестного элемента. Так, прогнав парсер на полном наборе HTML, можно будет увидеть все проблемные места. И при изменении разметки и появлении новых элементов в новых тредах парсер это обнаружит.

Также, при парсинге кода важно не потерять пробелы и переносы строк. 

Я могу попробовать этим заняться на неделе, если смогу разобраться с установкой и если найдется время.

Добавлю еще ссылку на issue #30

**Comment by kubk** [comment]
Спасибо за сообщение.

Да, текст поста в тестах проверяется частично, почти всегда через assertContains('часть поста', $post->getText()), как раз из-за пробелов и переносов строк, поэтому ошибка осталась незамеченной. Тут ещё важно то, что в некоторых HTML-файлах проще было отредактировать невалидный HTML, чем добавлять очередной if в парсер, так как сам парсер вышел гораздо более сложным, чем планировалось изначально. Я хочу сам глянуть 13-й тред, может удасться обойтись минимальным вмешательством в XPath-выражение.

> если смогу разобраться с установкой

Пример того, что нужно для прогона тестов есть в файле .travis.yml: https://github.com/richBlueElephant/phpClub/blob/master/.travis.yml
Если есть вопрос почему там создаётся .env файл через echo, а не выставляются переменные окружения средствами Travis - пакет vlucas/phpdotenv требует наличия файла .env
В Laravel разработчики просто заглушают ошибку: https://github.com/laravel/lumen/blob/master/bootstrap/app.php#L5
Думаю для нашего случая echo подходит лучше.

Для экономии времени я пользуюсь расширением для XPath:
- https://github.com/pierretholence/firepath
- https://addons.mozilla.org/en-US/firefox/addon/firepath/

**Comment by codedokode** [comment]
Отпишусь по прогрессу выполнения задачи. Я решил для начала вообще посмотреть, как со временем менялась верстка постов. Для этого я написал вспомогательный скрипт анализа верстки, который в итоге оказался чуть сложнее, чем я ожидал.

Если кому-то любопытно, то вот скрипт и там же есть файл лога с данными, которые он вывел: https://gist.github.com/codedokode/74335e366e3cf433314979bf8f9d33dd

Там показано, как менялась верстка поста с 1 по 98 треды.

Чтобы это определить, я для начала написал класс для сравнения фрагментов DOM и определения отличий. Сравниваются отдельно элементы, их атрибуты и CSS классы, и результат представляется в виде массива изменений (патча) - добавлений и удалений (как в традиционном diff для текста), применение которых позволяет преобразовать первый фрагмент во второй. На его основе я написал функцию, которая получает на вход 2 куска DOM и возвращает дерево, содержащее только общие элементы, которые присутствуют в обоих кусках.

После этого я брал где-то 20 постов из каждого треда и вычислял общий фрагмент DOM, этакую модель одного поста. Затем сравнивал эти модели постов для соседних тредов. 

Я думаю, что написанную в итоге библиотеку сравнения DOM можно будет потом выпустить как отдельный проект. 

По итогам анализа, получилось, что начиная с 30 треда верстка поста довольно сильно поменялась.

После этого я решил проверить, какие виды разметки есть в постах. Для этого я написал еще один скрипт, который выделял из поста его текст и анализировал, какие теги, атрибуты и классы там встречаются. Вот его код и результат работы: https://gist.github.com/codedokode/d4822525de5c272681fe0977de2af942

В ходе его работы я обнаружил проблемы с версткой в 1, 4b и 15 тредах - там местами верстка просто сломана и куски HTML перемешаны - я пока еще не решил, как с ними лучше поступить, подумаю позже. Пока я просто запустил анализ, начиная с 16 треда. Вот какую разметку я нашел в постах: 

- `<p>....</p>` - весь текст поста завернут в тег `<p>`
- `<br>`
- `<a href="..." rel="nofollow">...</a>` - ссылка
- `<a href="..." target="_blank">...</a>` - ссылка начиная с треда 30 (Авг 2014)
- `<strong>...</strong>`
- `<span class="unkfunc">...</span>` - цитата (зеленый цвет)
- `<a onmouseover="showPostPreview(event)" onmouseout="delPostPreview(event)" href="#315927" onclick="highlight(315927)">>>315927</a>` - ссылка на пост
- `<a href="#380394" class="post-reply-link" data-thread="377570" data-num="380394">>>380394</a>` - ссылка на пост начиная с треда 30 (Авг 2014)
- `<span class="spoiler">...</span>`
- `<em>...</em>`
- `<pre><code>....</code></pre>` - код, используется `<br>` для переноса строк
- `<sub>...</sub>`
- `<sup>...</sup>`
- `<span class="s">...</span>` - зачеркнутый текст
- `<span class="u">...</span>` - подчеркнутый текст?
- `<span class="o">...</span>` - надчеркнутый?
- `<font color="#C12267"><em>(Автор этого поста был забанен.. Помянем.)</em></font>` - с треда 24 (май 2014)
- `<span class="code_container"><span class="code_line">..</span><br>...</span>` - код начиная с треда 30 (Авг 2014)
- `<span class="pomyanem">(Автор этого поста был забанен.. Помянем.)</span>` - с треда 59 (Сент 2015)

Я планирую заложить в парсер список допустимых видов разметки и прерывать выполнение при обнаружении чего-то нестандартного. Это позволит обнаруживать ошибки в парсере или нововведения в верстке. Благодаря этому я как раз и обнаружил проблемы с версткой нескольких тредов. Также это позволит нам знать, какие CSS стили надо прописать для корректного отображения всех элементов разметки.

Итак, вот что я планирую сделать дальше: 

- доработать парсер, чтобы он брал весь текст поста со всей разметкой
- но при этом проверять теги в тексте и бить тревогу при обнаружении незнакомых тегов
- убирать скриптовые атрибуты вроде `onmouseover` со ссылок
- решить, что делать с тредами со сломанной версткой 
- сделать тесты, проверяющие парсинг текстов с различной разметкой

**Comment by codedokode** [comment]
И кстати, говоря про тесты, есть какие-то критерии, по которым отбирались треды сюда: https://github.com/richBlueElephant/phpClub/blob/master/tests/ThreadParser/DvachHtmlParserTest.php#L60  ? 

Я подумал, что можно будет по итогам анализа сократить этот список, оставить только сильно различающиеся треды. Чтобы те же тесты прогонялись быстрее.

**Comment by kubk** [comment]
@codedokode Спасибо, это нужно изучить.

> Благодаря этому я как раз и обнаружил проблемы с версткой нескольких тредов

Текущая версия парсера тоже сообщает об ошибках, можно глянуть по коду, тут для каждого элемента поста в случае неудачи вываливается исключение: https://github.com/richBlueElephant/phpClub/blob/master/src/ThreadParser/AbstractThreadParser.php#L114

Просто я вручную вмешивался в HTML 1-го и 4b треда, где-то правил HTML, где-то удалял посты, поэтому в тестах этих ошибок уже нет. Исправленные HTML: https://github.com/richBlueElephant/phpClub/tree/master/tests/Fixtures/dvach

> убирать скриптовые атрибуты вроде onmouseover со ссылок

Сейчас при парсинге для получения имени изображения, ширины и высоты используются аргументы, которые передаются в обработчик `onclick`: https://github.com/richBlueElephant/phpClub/blob/master/src/ThreadParser/DvachThreadParser.php#L63
Так что думаю onclick нужно оставить, либо разбирать ширину/высоту отдельно уже после парсинга: http://php.net/manual/en/function.getimagesize.php#refsect1-function.getimagesize-examples

> решить, что делать с тредами со сломанной версткой

ЕМНИП, в 15-м треде посты ещё продублированы по несколько раз, поэтому думаю можно добавить очередной if в парсер и убирать из треда повторяющиеся посты.

И да, библиотека пригодится отдельным пакетом.

**Comment by codedokode** [comment]
@kubk - по поводу ошибок при парсинге, я имел в виду "проверять DOM дерево **текста** поста на наличие элементов или атрибутов не из белого списка". Это позволит обнаруживать новые элементы в разметке и ошибки парсинга.

Про скриптовые атрибуты - я имел в виду только ссылки в теле поста такого вида `<a onmouseover="showPostPreview(event)" onmouseout="delPostPreview(event)" href="#315927" onclick="highlight(315927)">>>315927</a>`. Не ссылки на картинки.

**Comment by codedokode** [comment]
Отпишусь кратко по прогрессу задачи. Осталось написать тесты, которые бы тестировали парсинг выбранных постов из разных тредов, в том числе отдельных частей текста поста. У меня такая мысль, отобрать посты и для каждого поста выбрать пункты, которые тестируются, например: 

```
123456, title, Название поста
123457, trip, xnn2eu
123458, text, Кусок текста
```

Также, нужно для окончательной проверки прогнать парсер по всем имеющимся тредам из всех источников.

- добавлен проверяльщик разметки, который проверяет теги в теле поста. Благодаря нему обнаружено множество багов парсинга.
- написан скрипт, который исправляет сломанные треды 1, 4b и 15, более лучше, чем ранее ([исходничек](https://gist.github.com/codedokode/590f9094988bbd22db7164bb83e54405)). Он не внесен в репозиторий. В этих тредах по непонятной причине куски HTML кода как-то перемешаны, в том числе и так, что в них получаются оборванные куски разметки, что сбивает с толку DOM-парсер. Скрипт вначале удаляет из кода эти куски разметки, а затем проходится по постам и удаляет дубликаты. По какой-то причине там каждый пост продублирован 2 раза, причем в первый раз в нем куски разметки от какого-нибудь другого поста. Почему так вышло, мне непонятно, то ли тогда был баг на дваче, то ли это где-то у меня файлы побились, когда копировались с диска на диск.
- исправленные копии тредов 1, 4b, 15 добавлены в тесты
- доработана команда импорта, она умеет парсить без внесения изменений в БД, пропускать сломанные треды, и определять тип файла (m2-ch/arhivach/dvach). Выводит прогресс парсинга.
- добавлено восстановление закодированных cloudflare адресов email (наткнулся я на них благодаря проверяльщику разметки)
- при импорте при ошибке парсинга поста выводится его HTML-код
- перед импортом проверяется уникальность id постов внутри треда
- добавлен парсинг файлов m2-ch
- все старые тесты проходят

Если интересно, глянуть изменения можно на https://github.com/codedokode/phpClub/tree/42-parser-fixes

**Comment by kubk** [comment]
@codedokode Ого, проделана большая работа, спасибо. 

> php -S 127.0.0.1:9001 -t public ../dev-server.php
Не совсем понятно зачем тут две точки. Файл dev-server.php и папка public находятся ведь на одном уровне. Если запустить эту команду из корня проекта, то она ведь не будет работать?

**Comment by codedokode** [comment]
@kubk Может, зависит от версии PHP или от текущей папки, у меня не работало. Можешь попробовать выяснить, если хочешь.

Сегодня, тестируя парсинг всех тредов, я наткнулся на еще один сломанный тред (тред 4, m2-ch, из google cache). Сначала я хотел дописать еще правила в скрипт исправления сломанных тредов ( https://gist.github.com/codedokode/590f9094988bbd22db7164bb83e54405 ), но потом решил подойти к задаче с другой строны. Старый скрипт, напомню, основан на вручную найденных кусках невалидной разметки, которая вырезается из треда, затем он парсится и дубли постов удаляются. После чего из них генерируется новая копия треда.

Я уже раньше видел, что в файлах есть явно повторяющиеся куски кода, и решил попробовать автоматичеки поискать такие куски, и посмотреть, как они расположены, что идет до/после них, срастется ли HTML-код, если их вырезать. Есть ли какая-то логика в их расположении. И она - внезапно - нашлась!

Вот скрипт и созданные им "карты" кусков файлов: https://gist.github.com/codedokode/80913ab9d9279bf30878ff60c48515dc

Если мы возьмем самый маленький и простой тред: 

```
/tmp/threads/pr-thread-4-272705-m2ch-18-may-google.html
Total repeats: 185567 of 454322 bytes
     -         0 -  41080 | \n<meta http-equiv="Content-Type" content ... ss="reply" id="27307
 first  1  41081 -  85327 | 5"><div class="pst_bar"><span class="pos ... ://m2-ch.ru/pr/res/2
second  1  85328 - 129574 | 5"><div class="pst_bar"><span class="pos ... ://m2-ch.ru/pr/res/2
     -    129575 - 129593 | 72705.html#273385">
 first  2 129594 - 177012 | &gt;&gt;273385</a><br><br><span class="u ... ;А если надо сюда HT
     -    177013 - 177034 | 72705.html#273385"&gt;
second  2 177035 - 224453 | &gt;&gt;273385</a><br><br><span class="u ... ;А если надо сюда HT
     -    224454 - 224621 | ML-тегов с аттрибутами добавить? У тебя  ... виджет сделан.</span
 first  3 224622 - 270150 | ><br>Ну добавляешь, кто мешает? Компонен ... 59">&gt;&gt;275659</
     -    270151 - 270163 | ml-тегов
second  3 270164 - 315692 | ><br>Ну добавляешь, кто мешает? Компонен ... 59">&gt;&gt;275659</
 first  4 315693 - 364064 | a><br><br>Рад, что ты сам разобрался.<br ... ки несколько раз. <b
second  4 364065 - 412436 | a><br><br>Рад, что ты сам разобрался.<br ... ки несколько раз. <b
     -    412437 - 454321 | r><br>Это не виджеты, это один большой н ... ru&client=opera -->\n
```

Здесь first, second обозначают первый и второй повторяющиеся сегменты. Минус обозначает уникальные сегменты файла. Цифры показывают смещение сегментов в файле.

Мы видим явную логику: в файле дублируются фрагменты размером около 40 Кб. Причем, конец первого фрагмента сходится с тем, что идет за вторым фрагментом. То есть можно удалить каждый второй повторяющийся фрагмент и все красиво сходится.

В 1-й и 4-й группе повторяющиеся сегменты идут друг за другом без промежутков. В 2-й и 3-й группе сегментов в промежутке есть кусочек кода, но он является лишь искаженной копией идущего ранее кода. Если посмотреть на карты этого и других файлов, то мы увидим логику генерации этого кусочка: 

- либо символы переводятся в нижний регистр (`ML-тегов с аттрибутами...` -> `ml-тегов`)
- либо символы экранируются (`72705.html#273385">` -> `72705.html#273385"&gt;` и `дскажите, пожалуйста, решение` -> `одскажите&#44; пожалуйста&#44; решение` в файле pr-thread1.html)
- либо код пропускается через HTML парсер: `продолжение программы<br><br>` -> `продолжение программы<br /><br /` в файле pr-thread1.html
- причем иногда этот парсер ломается: `л я это создав производный класс` -> `л="" я="" это="" создав="" производный="` в файле pr-thread1.html

Поняв логику, нетрудно было дописать функцию исправления. В каждой паре сегментов мы удаляем второй сегмент и промежуток между ними, при условии что их размеры соответствуют заданным параметрам. Я проверил ее на 15 треде, пофиксив его и попробовав импортировать - все ок.

Тут конечно остается вопрос, как проверить, что файлы после восстановления получаются корректными и мы ничего не теряем? Я пока думаю ограничиться просто проверкой путем попытки импорта, так как парсер реагирует на любую постороннюю разметку в теле поста.

**Comment by codedokode** [comment]
Закрываю задачу, так как она решена. Если вдруг я что-то пропустил - можно переоткрыть задачу или создать новую.
