### ISSUE TITLE
Скрипт роутинга для встроенного веб-сервера

### ISSUE THREAD

**Issue by codedokode** [richBlueElephant/phpClub#43]
В репозитории нет скрипта роутинга для запуска проекта из-под встроенного в PHP веб-сервера. Я планирую его добавить (`/dev-server.php`) и добавить нужную команду в README, если нет возражений. 

За основу возьму 

- https://github.com/symfony/web-server-bundle/blob/master/Resources/router.php
- https://github.com/drupal/drupal/blob/8.5.x/.ht.router.php

**Comment by someApprentice** [comment]
Моё сердце радуется, потому что мой учитель делает вклад в проект, который я начал

Меня могут осудить за излишнюю сентиментальность, но мне не страшно
Ужасней было бы не выразить, как я к этому отношусь, и что это для меня значит

Спасибо

**Comment by codedokode** [comment]
Добавил пулл реквест, если надо, можно еще добавить команду запуска сервера в composer.json, только надо там убрать таймаут (так как от него по большому счету пользы нет). Я не стал добавлять, так как сам этой возможностью не пользуюсь.

**Comment by kubk** [comment]
@codedokode Спасибо, у нас для Slack настроены оповещения обо всех событиях в репозитории. Ещё можно в название коммита писать "Closes (#номер_issue)", тогда после мержда коммита в мастер issue автоматически закроется.
