### ISSUE TITLE
Тесты могут отваливаться по таймауту при запуске через композер

### ISSUE THREAD

**Issue by codedokode** [richBlueElephant/phpClub#44]
При запуске тестов командой composer test композер ставит таймаут в 300 секунд на выполнение: https://getcomposer.org/doc/06-config.md#process-timeout

Можно поменять таймаут в конфиге композера, но только глобально для всех скриптов. Думаю, лучше переписать в README команду на запуск тестов без использования composer. Я планирую так сделать, если нет других идей.

**Comment by foobar1643** [comment]
@codedokode У run-script есть CLI опция `--timeout`, с помощью которой можно отключить таймаут, или задать нужный.
https://getcomposer.org/doc/03-cli.md#run-script

Наверное просто стоит обновить README, дописав туда команду для запуска без таймаута.

**Comment by kubk** [comment]
Команду `composer run-script test --timeout=0` вбивать слишком долго по сравнению с `vendor/bin/phpunit`, поэтому скрипт лучше удалить.

**Comment by someApprentice** [comment]
@kubk пусть пользователи перечисленных проектов сами разбираются, какую команду им нужно вызывать

**Comment by kubk** [comment]
Я пользователь всех этих проектов на работе, гораздо проще когда есть одна команда для прогона всех тестов и не нужно вспоминать как её вызывать.

**Comment by codedokode** [comment]
Вообще, можно убрать таймаут в composer.json. Я не думаю, что от него какая-то польза есть, и если надо, его можно переопределить через командную строку. Я сам, впрочем, запуском через композер не пользуюсь, но если кому-то удобнее, то почему бы не сделать такую возможность.
