### ISSUE TITLE
Ошибка Sphinx при попытке вывода результатов с offset выше допустимого

### ISSUE THREAD

**Issue by someApprentice** [richBlueElephant/phpClub#54]
```
Type: PDOException
Code: 42000
Message: SQLSTATE[42000]: Syntax error or access violation: 1064 offset out of bounds (offset=1000, max_matches=1000)
File: /var/www/phpClub/src/Pagination/SphinxAdapter.php
Line: 61
```

Также, будет лучше, если сначала будут выводиться посты по актуальности, т.е. сначала новые.

**Comment by codedokode** [comment]
Там можно при обращении в Sphinx указывать в SQL-запросе `max_macthes`. В документации написано, что оно влияет на потребление памяти, но я не думаю что для 100 x 1000 = 100K постов и малого числа пользователей это как-то сильно повредит (ну, если что, можно будет просто померять потребление экспериментально, сделав поиск по популярному слову). 

Пример запроса с популярным словом: https://phpclub.tech/search/?q=php

Насчет порядка постов - я то же самое хотел предложить. И еще, можно подумать над пессимизацией ОП-постов, так как они все одинаковые, и наверно нет смысла вываливать 100 ОП постов, если кто-то ввел слово из них. А можно их хотя бы поместить в конец, а в идеале еще и сгруппировать в один. Или может выкинуть вообще из результатов.

Для определения порядка вывода постов в SQL-варианте используется `ORDER BY`, и там есть встроенная функция `WEIGHT()`, которая по-моему вычисляет "релевантность" результата запросу.

**Comment by someApprentice** [comment]
>Для определения порядка вывода постов в SQL-варианте используется ORDER BY, и там есть встроенная функция WEIGHT(), которая по-моему вычисляет "релевантность" результата запросу.

Функция WEIGHT() выводит посты в разноброс. 

Может при получении постов с помощью доктрины их перемешивает (`$posts = $this->postRepository->findBy(['id' => $ids]`), но, в любом случае, проще сориентироваться когда посты идут по порядку.

Поэтому,  я придержусь простой сортировке по дате.

**Comment by someApprentice** [comment]
При большом количестве результатов, выводиться большее количество страниц, чем есть на самом самом деле

https://phpclub.tech/search/?q=php&page=1025

Также, напомню для себя добавить заглушку, если ничего не найдено, с сообщением об этом

**Comment by kubk** [comment]
@someApprentice может проблема в том, что в пагинаторе используются разные запросы?
- https://github.com/richBlueElephant/phpClub/blob/master/src/Pagination/SphinxAdapter.php#L41
- https://github.com/richBlueElephant/phpClub/blob/master/src/Pagination/SphinxAdapter.php#L57
Они должны быть одинаковыми, но один запрос должен возвращать count, а второй - результаты поиска.

**Comment by kubk** [comment]
@codedokode через сфинкс как-то можно делать подсветку результатов? В Elasticsearch достаточно просто добавить в запрос ключ 'highlight': https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-highlighting.html#specify-fragmenter

Не нагуглил как это делать средствами сфинкс.

**Comment by codedokode** [comment]
@kubk Да, там есть подсвечивальщик.

При использовании SQL это `CALL SNIPPETS`: http://sphinxsearch.com/docs/latest/sphinxql-call-snippets.html . Он вызывается для одного индекса, потому, если поиск идет по нескольким с разными настройками обработки слов, может понадобиться сделать несколько вызовов.

При использовании API это BuildExcerpts: http://sphinxsearch.com/docs/latest/api-func-buildexcerpts.html

В HTML для подсветки предусмотрен тег `<mark>`.

**Comment by kubk** [comment]
@codedokode спасибо за подсвечивальщик.

Касательно пагинации - конечно, наш SphinxAdapter не переиспользуемый. Адаптер должен конвертировать один интерфейс другой и ничего более. Вот тут https://github.com/whiteoctober/Pagerfanta/pull/218 пример получше, но его не вмерджили из-за отсутствия тестов. Ну и он не использует `SHOW META LIKE`

> Напоминает SearchAdapter, при желании можно даже реализовать тут его интерфейс

Нужно его и реализовать, благодаря этому результат можно пагинировать и использовать код библиотеки Pagerfanta для формирования HTML, а не велосипедить. Pagerfanta уже используется для пагинации данных из БД.

Можно ещё заморочится с тем, чтобы SearchService ничего не знал про Pagerfanta - из SearchService возвращаем SearchResult, потом его адаптируем для Pagerfanta, но у нас не библиотека для всеобщего использования и думаю можно сделать по-простому:
```php

use Pagerfanta\Adapter\AdapterInterface;

class SearchService
{
    // возвращаем SearchResult, реализующий AdapterInterface
    public function search(string $query, ...): AdapterInterface
}
```

Ну и конечно нужно первым делом уточнить у @someApprentice , хочет ли он исправлять это, задача по рефакторингу и не первой важности, как по мне.

**Comment by someApprentice** [comment]
Кто-нибудь знает как лучше исправить ошибку `FATAL: failed to open /var/lib/sphinxsearch/data/src_posts.spl: Permission denied, will not index. Try --rotate option.` при выполнении `indexer --config config/sphinx.conf --all`?
Это же просто отсутсвие прав на данную директорию, для пользовотателя с которого выполняется данная команда. Владелец этой дироктрии - пользователь sphinxsearch, поэтому можно предположить что , и можно:
1. Выпонлять эту комманду через sudo (как я делаю это обычно)
1. Поменять владельца директории
1. Поменять пути в файле конфигруции (которые взяты с премера предлгаемым самим Sphinx'ом)
1. Может есть способ элегантней?

**Comment by codedokode** [comment]
@someApprentice если используется общесистемный сфинкс, то наверно придется использовать sudo. Другие варианты - поменять права на папку, дав доступ к ней определенной группе пользователей (например, sphinx-users) или использовать не общесистемный, а выделенный для проекта сфинкс, который запускается от того же пользователя, что и php-сервер.

**Comment by someApprentice** [comment]
> @codedokode спасибо за подсвечивальщик.
> 
> Касательно пагинации - конечно, наш SphinxAdapter не переиспользуемый. Адаптер должен конвертировать один интерфейс другой и ничего более. Вот тут [whiteoctober/Pagerfanta#218](https://github.com/whiteoctober/Pagerfanta/pull/218) пример получше, но его не вмерджили из-за отсутствия тестов. Ну и он не использует `SHOW META LIKE`
> 
> > Напоминает SearchAdapter, при желании можно даже реализовать тут его интерфейс
> 
> Нужно его и реализовать, благодаря этому результат можно пагинировать и использовать код библиотеки Pagerfanta для формирования HTML, а не велосипедить. Pagerfanta уже используется для пагинации данных из БД.
> 
> Можно ещё заморочится с тем, чтобы SearchService ничего не знал про Pagerfanta - из SearchService возвращаем SearchResult, потом его адаптируем для Pagerfanta, но у нас не библиотека для всеобщего использования и думаю можно сделать по-простому:
> 
> ```
> 
> use Pagerfanta\Adapter\AdapterInterface;
> 
> class SearchService
> {
>     // возвращаем SearchResult, реализующий AdapterInterface
>     public function search(string $query, ...): AdapterInterface
> }
> ```
> 
> Ну и конечно нужно первым делом уточнить у @someApprentice , хочет ли он исправлять это, задача по рефакторингу и не первой важности, как по мне.
