### ISSUE TITLE
Билдер для сущности Post

### ISSUE THREAD

**Issue by someApprentice** [richBlueElephant/phpClub#57]
При создании сущности Post передаётся большое количество аргументов. Соответственно, нужно написать для этого билдер.

**Comment by kubk** [comment]
Я сейчас читаю много про DDD и понимаю, что если всё делать по уму без сеттеров и геттеров, то нужно переделывать очень многое в проекте, для не знакомых с DDD такой проект будет запутанным и непонятным. Важно учитывать, что код проекта будут смотреть много начинающих из треда. Поэтому я перепишу код на более привычный для всех подход с сеттерами, а с DDD буду играться в своих проектах, где мои подходы не будут никого тормозить.

**Comment by codedokode** [comment]
@kubk может для пробы - переделать один какой-то класс, а не весь проект? Если код будет выглядеть логично и понятно, и его легко писать, я например, проблем не вижу, хотя с DDD не работал.

**Comment by kubk** [comment]
https://github.com/richBlueElephant/phpClub/commit/7a4050f271f4e0eb4fcc8b535c064ea4ebab309f

@codedokode В этом проекте есть более важные задачи и проблемы, которые нужно решить. А свои эксперименты может как-нибудь опубликую на ревью.
