### ISSUE TITLE
Автоматическая фильтрация NSFW контента

### ISSUE THREAD

**Issue by foobar1643** [richBlueElephant/phpClub#61]
Наш хостер тут недавно приостановил работу сервиса, из-за того что NSFW контент нарушает правила пользования их хостингом. Контент @someApprentice вроде как вручную удаляет, но из-за этого возникает вопрос - как быть дальше? Если в каком-то новом треде будут постить что-то нехорошее, мы можем его спарсить и не заметить, тогда история повторится (или хостинг вообще отключат за несколько одинаковых нарушений правил).

Я думаю можно попробовать сделать автоматическое распознавание NSFW контента, и подсовывать заглушку на место таких картинок.

У Yahoo есть нейросеть, которая оценивает картинки по NSFW Score:

https://github.com/yahoo/open_nsfw

Предлагаю для начала попробовать такой вариант, у них в репозитории уже есть готовая модель, нужно только проверить работоспособность и адекватность оценки.

Может быть у кого есть другие варианты, можно обсудить тут. Еще предлагался ручной вариант модерации, но вряд ли кто-то будет этим заниматся.

**Comment by kubk** [comment]
> The network takes in an image and gives output a probability
То есть видео не поддерживаются? Я когда парсер писал, то натыкался на откровенный треш  уровня /b именно в видео, помню даже хотел из-за этого видео не учитывать при парсинге, мы это ещё в гиттере обсуждали.

ping @codedokode 
Есть идеи?

@someApprentice от хостера есть ответ?

**Comment by someApprentice** [comment]
От хостера до сих пор нету ответа

Я немедленно сообщу если появиться какие либо новости

**Comment by codedokode** [comment]
@foobar1643 Если есть такая возможность, то проще всего поменять хостера. Если этот контент не противоречит местным законам, я вообще не понимаю, в чем проблема и чего они из себя взялись строить поборников морали.

Каких-то надежных вариантов я не знаю, ну если только действительно взять ту модель и как-то скриптом в офлайне проверять и помечать картинки. Даже в фейсбуке и гугле модерацией люди занимаются. Еще можно сделать какой-то скрипт, который выведет сеткой все картинки и вручную их помечать - это может быстрее оказаться.

Вместо удаления лучше бы только скрывать контент, чтобы в случае смены хостинга можно было открыть его обратно.

**Comment by codedokode** [comment]
По видео - можно его нарезать на кадры через 1-5 секунд и проверять их.

**Comment by codedokode** [comment]
А какие системные требования у phpclub? Память, CPU, место на диске? Я могу попробовать поискать какой-то временный VPS на период, пока ситуация не изменится.

**Comment by someApprentice** [comment]
@codedokode мы решили разместить сервер у @foobar1643 

Сегодня вечером попытаемся развернуть в тестовом режиме

!Важно: Могут быть перебои в работе ненадолго

**Comment by codedokode** [comment]
> !Важно: Могут быть перебои в работе ненадолго

Если учесть, что он в приципе не работает, то это не страшно. Если вдруг не получится, я готов поискать какой-нибудь VPS под это дело.

**Comment by kubk** [comment]
Взяли другой VPS, проблема не должна возникать. Пока там только один тред, вскоре добавим старые из архива.
