### ISSUE TITLE
Получение URL из сервиса.

### ISSUE THREAD

**Issue by kubk** [richBlueElephant/phpClub#66]
@someApprentice 
https://github.com/richBlueElephant/phpClub/blob/17321e6970fc62460d06e43d3fa436849221b1cf/templates/base/footer.phtml#L29

Можно ли здесь не зашивать URL, а использовать существующий метод генерации ссылки на архивач?
https://github.com/richBlueElephant/phpClub/blob/16e1b72645c138a99915177d7d0f4a6989a04aa8/src/BoardClient/ArhivachClient.php#L89+L92

**Comment by someApprentice** [comment]
Имеешь ввиду, сделать такую же функцию на js? Конечно, почему нет.

**Comment by kubk** [comment]
@someApprentice Вынесение в отдельную функцию тут вряд ли чем-то поможет. Я за то, чтобы был "The single source of truth" и поэтому спрашиваю, можно ли как-то это здесь организовать.

**Comment by someApprentice** [comment]
@kubk, это шаблон для js, который нужен для вывода превью поста, при получении его из API, поэтому PHP-код здесь не имеет места.

https://github.com/richBlueElephant/phpClub/blob/master/public/media/js/script.js#L177

Если ты хочешь чтобы в нём было как и PHP-шаблоне, то я могу попробывать вынести это в отдельную функцию.

**Comment by kubk** [comment]
@someApprentice можно в ArhivachClient добавить метод для получения строки "http://arhivach.cf/ajax/?act=locate_thread&url=" или "http://arhivach.org/ajax/?act=locate_thread&url=" и через PHP отрендерить HTML? Тут явное дублирование, которое я бы даже не заметил, если бы не сделал поиск по проекту.

**Comment by someApprentice** [comment]
@kubk, я уловил твою мысль.

Может, если мы хотим предерживаться "The single source of truth", то стоит отредактировать уже существуюий метод, который теперь будет возвращать, привёденную тобой в пример, строку, и в PHP-шаблоне писать также `<a href="<?= $urlGenerator->toArhivachThread() ?>https://2ch.hk/pr/res/<?= $post->getThread()->getId() ?>.html">...</a>`?

P.S.
Почему в PHP-шаблоне мы до сих пор не используем этот метод? https://github.com/richBlueElephant/phpClub/blob/17321e6970fc62460d06e43d3fa436849221b1cf/templates/post.phtml#L28
Как раз с этой задачей исправим и эту проблему.

**Comment by kubk** [comment]
Там изначально использовался ` $urlGenerator->toArhivachThread()`
А в коммите "Frontend refactoring" был убран: 
https://github.com/richBlueElephant/phpClub/commit/c2f82b5203b866dd0cdcfb1b788e3710d999a512#diff-d849d03dcb652291948598315700fedd

**Comment by someApprentice** [comment]
My bad

@kubk, что насчёт редактирования метода `toArhivachThread()`? Ты не против этой идеи?

**Comment by kubk** [comment]
@someApprentice можешь 2 метода сделать, можешь старый исправить, как проще.
