### ISSUE TITLE
Рефакторинг сервиса авторизации

### ISSUE THREAD

**Issue by foobar1643** [richBlueElephant/phpClub#8]
Сейчас сервис написан с завязкой на глобальные переменные вроде $_COOKIES, $_POST и $_SERVER, это неправильно, особенно когда у нас проект на фреймворке, который предоставляет абстракции над HTTP запросом и ответом.

Нужно сделать:
* Работать с куками через PSR-7 объекты Request и Response, не использовать суперглобал $_COOKIES и функцию setcookie().
* Работать с телом POST запроса через объект Request, не использовать суперглобал $_POST.
* Убрать проверки на REQUEST_METHOD в сервисе, не использовать суперглобал $_SERVER.

В идеале должен получится сервис авторизации, который работает с объектами Request и Response, при этом ему все равно откуда они передались, сервис ничего не делает с глобальными переменными.

**Comment by kubk** [comment]
Добавлю, что в популярных фреймворках стандартно пароль хешируется/проверяется через password_hash/password_verify, а это значит, что для сущности User не нужно генерировать соль и хранить её в отдельном столбце, соль уже будет находится внутри хеша.

**Comment by kubk** [comment]
Закрываю, чтобы не сбивать новых людей с толку. В слаке обсуждали возможный переход на SF4, который по своей сути тоже микрофреймворк, поэтому будем использовать компоненты симфони.
