### ISSUE TITLE
Проблемы с поиском

### ISSUE THREAD

**Issue by codedokode** [richBlueElephant/phpClub#87]
[Поиск по слову "будильник"](https://phpclub.tech/search/?q=%D0%B1%D1%83%D0%B4%D0%B8%D0%BB%D1%8C%D0%BD%D0%B8%D0%BA) не выдает [это сообщение](https://phpclub.tech/pr/res/1232710.html#1263399). Подозреваю, по каким-то причинам не обновились индексы сфинкса.

**Comment by someApprentice** [comment]
tl;dr: Исправленно и хотелось бы услышать, почему потребовалась создавать новую базу данных, что стало причиной этой проблемы.


Запустил индексер вручную и ничего не поменялиось, и никаких ошибок при этом не было.

Похоже, последния запись которая индексируется это с ID - [1206020](https://phpclub.tech/pr/res/1199390.html#1206020), которая датируется 8 июня.

Я так же обнаружил, что последняя запись, которая сделана в основной базе данных, тоже нахоидться под ID - 1206020. (Как это возможно?)

Заглянув в файл настроек соеденений я обнаружил, что соедение совершается с другой базой данных phpClub**2**.

Поменяв настройки Сфинкса перезапустил индексирование и пост [появился](https://phpclub.tech/search/?q=%D0%91%D1%83%D0%B4%D0%B8%D0%BB%D1%8C%D0%BD%D0%B8%D0%BA).

Хотел бы услышать комментарии почему потребовалась новая база данных и проблему можно закрывать.
