### ISSUE TITLE
Рефакторинг сервиса работы с ссылками на архивы

### ISSUE THREAD

**Issue by foobar1643** [richBlueElephant/phpClub#9]
Сейчас сервис написан с завязкой на глобальные переменные вроде $_POST и $_SERVER, это неправильно, особенно когда у нас проект на фреймворке, который предоставляет абстракции над HTTP запросом и ответом. Так же, на формах добавления\удаления архивных ссылок нет обработки ошибок, если не удалось добавить ссылку происходит просто реддирект на главную.

Нужно сделать:
* Работать с телом POST запроса через объект Request, не использовать суперглобал $_POST.
* Убрать проверки на REQUEST_METHOD в сервисе, не использовать суперглобал $_SERVER.
* Если не удалось добавить ссылку, возвращать массив ошибок, которые потом можно будет отобразить на View.
* В методе removeLink() передавать ID удаляемой ссылки аргументом, сервис не должен ничего знать про URL и никак не должен с ним работать.

**Comment by someApprentice** [comment]
Добавление\удаление ссылок планировалось осуществляться модератором. Предполагалось что модератор должен знать как это работает и допустить ошибку только по случайности, либо злоумышленником через CSRF-уязвимость. 

Сейчас пользователей с уровнем модератора как таковых нет - на сайте phpclub.rf.gd просто отключена регистрация. Эта возможность будет добавлена при реализации чата.

Хотя, сейчас я поймал себя на мысли, что, все таки, ошибки должны выводиться и для модераторов.

**Comment by someApprentice** [comment]
@kubk предлагает идею с автоматическим получением ссылок. Предлагаю продолжить обсуждение этого в этой теме.

**Comment by kubk** [comment]
> Ссылка на /chain/ стоит на значке № и хрен догадаешься, что она там есть. Лучше сделать ее более заметной, например, сделав надпись "цепочка сообщений" или как-то еще.

Нужно как-то отделять ссылку на пост, от ссылки на цепочку сообщений. Предлагаю для цепочки использовать иконку из Font Awesome: https://www.w3schools.com/icons/tryit.asp?filename=tryicons_fa-chain

А для поста номер - №1097471

**Comment by kubk** [comment]
Архивач умеет генерировать ссылки на архив, на основе URL треда на 2ch.hk
С архивом 2ch.hk - проблемней. Там проще всего вбить название треда в поиск (POST запрос), и спарсить оттуда URL.

**Comment by someApprentice** [comment]
@kubk в DvachApiClient будет систематичней

**Comment by codedokode** [comment]
Я тут мимо проходил и хотел обратить внимание, что если использовать Symfony Forms, то там есть защита от CSRF + какая-то валидация + маппинг данных формы на сущности Доктрины. Плюс, там есть код для вывода формы с использованием того же бутстрапа (если речь об админке, то бутстрап хорошее решение). То есть для написания админок самое то.

**Comment by kubk** [comment]
Нужно добавить поиск тредов в архиве 2ch.hk - и issue можно закрывать.
