### ISSUE TITLE
Рефакторинг хлебных крошек

### ISSUE THREAD

**Issue by someApprentice** [richBlueElephant/phpClub#90]
Хлебные крошки выполнены _смертельно_ просто - [в массив помщеается ключ => значение](https://github.com/richBlueElephant/phpClub/blob/838cbca395b06d1819c4d0f21f46b922793e2025/src/Controller/BoardController.php#L147-L149), где ключем выступает текстовое обозначение "крошки", а значением ссылка на раздел.

В такой реализации легко ошибиться. Нужно написать переиспользуемую обёртку над этим массивом.

Минимальный набор методов для этой обёртки:

- addCrumb(string $title, string $url): self

- getAllBreadCrumbs(): array

И было бы великолепно, если бы кто-нибудь придумал для них красивый дизайн.

**Comment by kubk** [comment]
Пример простого дизайна: 
![image](https://user-images.githubusercontent.com/22447849/46499920-259c9300-c82a-11e8-90c1-0192e699fa8c.png)

**Comment by kubk** [comment]
https://github.com/richBlueElephant/phpClub/pull/91
