### ISSUE TITLE
В теле страницы ссылка на несуществующий скрипт

### ISSUE THREAD

**Issue by codedokode** [richBlueElephant/phpClub#97]
При загрузке страницы https://phpclub.tech/pr/res/1268753.html в консоли ошибка 404 для файла https://phpclub.tech/media/js/templates/post.js 

Код:

```html
<script id="post-template" type="text/template" src="/media/js/templates/post.js">
<div id="<%= post.id %>" class="post <% if (post.isFirstPost) { %> op-post <% } %> clearfix" data-id="<%= post.id %>">
```

Атрибут  `src`, наверно, не нужен? 

Проблема есть и в FF52, и в Chromium парулетней давности.

**Comment by kubk** [comment]
Спасибо, видимо старый код, grep и find не нашли совпадений.
